# Generated by Django 5.1.4 on 2025-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_prevu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
